#
# Makefile for the Realtek network device drivers.
#

#obj-$(CONFIG_8139CP) += 8139cp.o
#obj-$(CONFIG_8139TOO) += 8139too.o
#obj-$(CONFIG_ATP) += atp.o
obj-$(CONFIG_R8169) += r8169.o
#ifeq ($(CONFIG_SYNO_LSP_RTD129X),y)
#obj-$(CONFIG_R8169SOC) += r8169soc.o
#endif # CONFIG_SYNO_LSP_RTD129X
#ifeq ($(CONFIG_SYNO_LSP_RTD1619),y)
#obj-$(CONFIG_R8168) += r8168/
#obj-$(CONFIG_R8168_PG) += r8168_pg/
obj-$(CONFIG_R8125) += r8125/
#obj-$(CONFIG_R8169SOC) += r8169soc_1619.o
#endif # CONFIG_SYNO_LSP_RTD1619
